module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🧩', '🍉', '💜', '🌸', '🪴', '💊', '💫', '🍂', '🌟', '🎋', '😶‍🌫️', '🫀', '🧿', '👀', '😘', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💗'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/KRyARlvcUjoIv1CPSSyQA5?mode=ems_copy_t',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://files.catbox.moe/otx26d.jpg',
    NEWSLETTER_JID: '120363348739987203@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: 'Arslan-Mini-Bot ',
    OWNER_NAME: 'Arslan-MD',
    OWNER_NUMBER: '923237045919',
    BOT_VERSION: '1.0.0',
    BOT_FOOTER: '> © 𝒫𝑜𝓌𝑒𝓇𝑒𝒹 𝐵𝓎 𝒜𝓇𝓈𝓁𝒶𝓃𝑀𝒟',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029VarfjW04tRrmwfb8x306',
};
